name: Generate html and deploy

on:
  push:
    branches: [$default-branch]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: Generate html with djinja2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Jinja2 Templating
        uses: jayamanikharyono/jinja-action@v1.1
        with:
          datafile: tests/data.json
          path: dist/*.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist