name: build and deploy

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    name: Generate html with djinja2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install python requirements
        run: pip install -r requirements.txt
        shell: sh

      - name: Install libreoffice
        run: sudo apt install libreoffice-calc

      - name: Download sheets ods
        run: wget https://docs.google.com/spreadsheets/d/1gt70J1CnQlIAVEpQT0LjjedoS4oo3p1vAPYQG2qLoKk/export?exportFormat=ods -O export.ods

      - name: Convert ods to xlsx
        run: libreoffice --convert-to xlsx export.ods

      - name: Export paintings data from xlsx file
        run: python mainexport_to_json.py
        shell: sh

      - name: Jinja2 Templating
        uses: jayamanikharyono/jinja-action@v1.1
        with:
          datafile: data.json
          path: dist/*.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2