name: Generate html

jobs:
  update:
    name: Generate html with djinja2

    steps:
    - name: Jinja2 Templating
      uses: jayamanikharyono/jinja-action@v1.1
      with:
        datafile: test/data.json
        path: test/index.html