name: Generate html

on:
  push:
    branches:
      - main

jobs:
  update:
    name: Generate html with djinja2
    runs-on: ubuntu-latest

    steps:
    - name: Jinja2 Templating
      uses: jayamanikharyono/jinja-action@v1.1
      with:
        datafile: test/data.json
        path: test/index.html